### ISSUE TITLE
package source on npmjs

### ISSUE THREAD

**Issue by fanatid** [mappum/peer-exchange#1]
@mappum please add `homepage` or `repository` to `package.json`

**Comment by fanatid** [comment]
oh, probably it's affect not only this package published by you..

**Comment by fanatid** [comment]
![screenshot at 2016-03-14 21 11 57](https://cloud.githubusercontent.com/assets/2633065/13754882/b58a11a4-ea29-11e5-9248-098abaf7e78d.png)

<hr>

![screenshot at 2016-03-14 21 13 30](https://cloud.githubusercontent.com/assets/2633065/13754883/b58f412e-ea29-11e5-9f9b-5fe6ffb390e6.png)

**Comment by mappum** [comment]
I'll go through and do this for all the repos. The reason I don't have that is because I usually `npm init` before I've created a repo on GitHub.

**Comment by mappum** [comment]
Done: d81c2998ace216cdbf6470c1ccb1096f5dfb44db
